# Generated by Django 5.1.5 on 2025-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='notification_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
