# Generated by Django 5.1.5 on 2025-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activitylog_notification_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
