# Generated by Django 5.1.5 on 2025-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_activitylog_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default-avatar.png', upload_to='profile_pictures/'),
        ),
    ]
