# Generated by Django 5.1.5 on 2025-02-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cover',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
