# Generated by Django 5.1.5 on 2025-02-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectprogress',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='progress_updates/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project'),
        ),
    ]
