services:
  - type: web
    name: visual-arts-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn visual_arts_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: visual-arts-db
          property: connectionString
databases:
  - name: visual-arts-db
