# Generated by Django 5.1.5 on 2025-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('canvas', 'Canvas'), ('wallart', 'Wall Art'), ('digital', 'Digital'), ('photography', 'Photography')], default='sketch', max_length=20),
        ),
    ]
