# Generated by Django 5.1.5 on 2025-06-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-submission_date']},
        ),
    ]
