# Generated by Django 5.1.5 on 2025-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # This AddField operation was causing the duplicate column error.
        # The column is already created in 0001_initial.py.
        # If 0002 was meant to ALTER this field, it should have been an AlterField operation.
        # Since 0003 is an AlterField, it seems 0002 was just wrongly generated.
    ]