# Generated by Django 5.1.5 on 2025-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                max_length=50,
                choices=[('event_update', 'Event Update'), ('project_update', 'Project Update')],
                default='event_update',
            ),
        ),
    ]
