# Generated by Django 5.1.5 on 2025-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20250205_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('artwork_approved', 'Artwork Approved'), ('event_update', 'Event Update'), ('project_invite', 'Project Invitation')], max_length=20),
        ),
    ]
